default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: sample_app_1_development

test:
  <<: *default
  database: sample_app_1_test

production:
  <<: *default
  database: sample_app_1_production
  username: sample_app_1
  password: <%= ENV["SAMPLE_APP_1_DATABASE_PASSWORD"] %>
